// Code generated by mockery. DO NOT EDIT.

package api

import mock "github.com/stretchr/testify/mock"

// MockOpts is an autogenerated mock type for the Opts type
type MockOpts struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockOpts) Execute(_a0 *Client) {
	_m.Called(_a0)
}
